"""add discovered_media and browse job types

Revision ID: 0f961eab400c
Revises: c26c27cf336b
Create Date: 2026-08-16 01:20:33.625251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f961eab400c'
down_revision: Union[str, None] = 'c26c27cf336b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Alembic's autogenerate does NOT detect added values on a MySQL ENUM column,
# so the job_type widening below is written by hand. Without it, inserting a
# discover/download-selected job fails at runtime with a data-truncated error.
_JOB_TYPES_NEW = (
    'SYNC_PROFILE', 'DOWNLOAD_POSTS', 'DOWNLOAD_REELS', 'DOWNLOAD_STORIES',
    'DOWNLOAD_SINGLE_POST', 'DISCOVER_POSTS', 'DISCOVER_REELS',
    'DISCOVER_STORIES', 'DOWNLOAD_SELECTED',
)
_JOB_TYPES_OLD = (
    'SYNC_PROFILE', 'DOWNLOAD_POSTS', 'DOWNLOAD_REELS', 'DOWNLOAD_STORIES',
    'DOWNLOAD_SINGLE_POST',
)


def _enum_sql(values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{value}'" for value in values)
    return f"ALTER TABLE download_jobs MODIFY job_type ENUM({joined}) NOT NULL"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instagram_media_id', sa.String(length=64), nullable=False),
    sa.Column('shortcode', sa.String(length=64), nullable=True),
    sa.Column('media_kind', sa.Enum('POST', 'REEL', 'STORY', name='mediakind'), nullable=False),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('is_carousel', sa.Boolean(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instagram_media_id', name='uq_discovered_media')
    )
    op.create_index(op.f('ix_discovered_media_account_id'), 'discovered_media', ['account_id'], unique=False)
    op.create_index(op.f('ix_discovered_media_instagram_media_id'), 'discovered_media', ['instagram_media_id'], unique=False)
    op.create_index(op.f('ix_discovered_media_media_kind'), 'discovered_media', ['media_kind'], unique=False)
    op.create_index(op.f('ix_discovered_media_shortcode'), 'discovered_media', ['shortcode'], unique=False)
    op.create_index(op.f('ix_discovered_media_taken_at'), 'discovered_media', ['taken_at'], unique=False)
    # ### end Alembic commands ###
    op.execute(_enum_sql(_JOB_TYPES_NEW))


def downgrade() -> None:
    op.execute("DELETE FROM download_jobs WHERE job_type NOT IN "
               "('SYNC_PROFILE','DOWNLOAD_POSTS','DOWNLOAD_REELS',"
               "'DOWNLOAD_STORIES','DOWNLOAD_SINGLE_POST')")
    op.execute(_enum_sql(_JOB_TYPES_OLD))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_media_taken_at'), table_name='discovered_media')
    op.drop_index(op.f('ix_discovered_media_shortcode'), table_name='discovered_media')
    op.drop_index(op.f('ix_discovered_media_media_kind'), table_name='discovered_media')
    op.drop_index(op.f('ix_discovered_media_instagram_media_id'), table_name='discovered_media')
    op.drop_index(op.f('ix_discovered_media_account_id'), table_name='discovered_media')
    op.drop_table('discovered_media')
    # ### end Alembic commands ###
