"""initial schema

Revision ID: be9112598e3e
Revises: 
Create Date: 2026-08-15 23:52:50.444270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9112598e3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ig_username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_session_blob', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_sessions_ig_username'), 'instagram_sessions', ['ig_username'], unique=False)
    op.create_table('tracked_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('profile_pic_path', sa.String(length=1024), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=1024), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('posts_count', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_accounts_username'), 'tracked_accounts', ['username'], unique=True)
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('SYNC_PROFILE', 'DOWNLOAD_POSTS', 'DOWNLOAD_REELS', 'DOWNLOAD_STORIES', 'DOWNLOAD_SINGLE_POST', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_account_id'), 'download_jobs', ['account_id'], unique=False)
    op.create_index(op.f('ix_download_jobs_celery_task_id'), 'download_jobs', ['celery_task_id'], unique=False)
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('POST_IMAGE', 'POST_VIDEO', 'CAROUSEL_IMAGE', 'CAROUSEL_VIDEO', 'REEL', 'STORY_IMAGE', 'STORY_VIDEO', name='mediatype'), nullable=False),
    sa.Column('instagram_media_id', sa.String(length=64), nullable=False),
    sa.Column('shortcode', sa.String(length=64), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.Column('download_timestamp', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('carousel_group_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['tracked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'instagram_media_id', name='uq_account_media')
    )
    op.create_index(op.f('ix_media_items_account_id'), 'media_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_media_items_carousel_group_id'), 'media_items', ['carousel_group_id'], unique=False)
    op.create_index(op.f('ix_media_items_instagram_media_id'), 'media_items', ['instagram_media_id'], unique=False)
    op.create_index(op.f('ix_media_items_shortcode'), 'media_items', ['shortcode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_items_shortcode'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_instagram_media_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_carousel_group_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_account_id'), table_name='media_items')
    op.drop_table('media_items')
    op.drop_index(op.f('ix_download_jobs_celery_task_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_account_id'), table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index(op.f('ix_tracked_accounts_username'), table_name='tracked_accounts')
    op.drop_table('tracked_accounts')
    op.drop_index(op.f('ix_instagram_sessions_ig_username'), table_name='instagram_sessions')
    op.drop_table('instagram_sessions')
    # ### end Alembic commands ###
